apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: java-spring-boot
spec:
  git:
    ref:
      branch: main
    url: https://github.com/robertocolella/awesome-tap-accelerators
    subPath: java-spring-boot